# nome file immagine => id della pagina
{
  "1"   => 1,
  "webdesign"   => 45,
  "2"   => nil,
  "grficaeditoriale"   => 30,
  "3"   => nil,
  "illustrazione"   => 43,
  "4"   => nil,
  "autocad"   => 49,
  "5"   => nil,
  "photoshop"   => 44,
  "6"   => nil,
  "3dstudiomax"   => 50,
  "7"   => nil,
  "sketchup"   => 48,
  "8"   => nil,
  "vray"   => 13,
  "9"   => nil,
  "10"  => nil,
  "11"  => nil,
  "12"  => nil,
  "13"  => nil,
}