development:
  database: cappiello_development
  adapter: mysql
  username: root
  password:
  host:     127.0.0.1

test:
  database: cappiello_test
  adapter: mysql
  username: root
  password:
  host:     localhost

production:
  database: cappiello_production
  adapter: mysql
  username: root
  password: secret
  host:     127.0.0.1

staging:
  database: cappiello_staging
  adapter: mysql
  username: root
  password: secret
  host:     localhost
